### ISSUE TITLE
Encoding problem for all application

### ISSUE THREAD

**Issue by AndreyNick** [Kirill241000/ducati_web#1]
Encoding problem
![image](https://user-images.githubusercontent.com/4988363/224276755-6c280d08-196a-487c-815c-8680ff839505.png)

**Comment by andrii-nikitin** [comment]
Rootcause: wrong encoding in **meta charset** tag.
Now: meta charset="**UFT**-8"
Should be: meta charset="**UTF**-8"

**Comment by Kirill241000** [comment]
solved the coding problem
