### ISSUE TITLE
Typo in project name

### ISSUE THREAD

**Issue by AndreyNick** [Kirill241000/ducati_web#2]
We have decided to name our project ducati_web, but the name is du**k**ati_web
Even Idea shows that there is a typo: 
![image](https://user-images.githubusercontent.com/4988363/224284165-4eb605fb-5bc9-437d-9ccd-35e60ba14663.png)

Need to correct the project name

**Comment by Kirill241000** [comment]
I changed the name of the repository from dukati_web to ducati_web and re-uploaded it to the idea
