### ISSUE TITLE
Cyrillic symbols in files name

### ISSUE THREAD

**Issue by AndreyNick** [Kirill241000/ducati_web#3]
Cyrillic symbols in files name are prohibited.
There is a small article regarding the topic: https://netology-university.bitbucket.io/codestyle/naming/
Need to rename all the files in project

**Comment by andrii-nikitin** [comment]
![image](https://user-images.githubusercontent.com/4988363/224293848-54c6d1cc-0ed1-44e8-8096-6dc4f62bf7a7.png)

**Comment by Kirill241000** [comment]
renamed all files
