### ISSUE TITLE
index.css problem

### ISSUE THREAD

**Issue by AndreyNick** [Kirill241000/ducati_web#4]
You may see that Idea has underlined the file index.css.
![image](https://user-images.githubusercontent.com/4988363/224285951-9631e109-a6a2-4817-9d27-f56fe3041518.png)
It means some problems in the file.
After opening the file you can see the same red underline: 
![image](https://user-images.githubusercontent.com/4988363/224286158-7a51c9fa-c95c-4fa0-8113-c9c6ddba494a.png)
It means that CSS doesn't support that type of parameter. Please fix it.

**Comment by Kirill241000** [comment]
removed unnecessary
